#!/bin/sh

# To add this Git Hook to your project, create a symlink:
# Windows: mklink /H pre-push ..\..\.githooks\pre-push

# Update version in manifest.json before pushing
node ".githooks/updateVersion.js"

# Add manifest.jon to staging
git add "src/manifest.json"

# Commit the changes
git commit -m "Update Version Number"

# Remove old zip file
git rm "AutoplayStopper(MV3).zip"

# Create zip
git archive -o "AutoplayStopper(MV3).zip" main:src --add-file=README.md
