#!/bin/sh

# Update version in manifest.json before pushing
node .tasks/updateVersion.js

# Add manifest.jon to staging
git add manifest.json

# Commit the changes
git commit -m "Update Version Number"

# Create zip
git archive -o "AutoplayStopper(MV3).zip" main

# Remove unnecessary files from zip
7za d "AutoplayStopper(MV3).zip" .*
7za d "AutoplayStopper(MV3).zip" assets
